version: "2"

linters:
  disable:
    - errcheck
  enable:
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - bodyclose
    - durationcheck
    - errname
    - nilerr
    - unconvert
    - wastedassign

linters-settings:
  gocritic:
    enabled-checks:
      - dupImport
      - ifElseChain
      - nestingReduce
      - truncateCmp

issues:
  exclude-dirs:
    - vendor
  max-issues-per-linter: 20
  max-same-issues: 5
